# Generated by Django 4.1.2 on 2022-10-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='Название категории')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=20, verbose_name='Логин пользователя')),
                ('user_password', models.CharField(max_length=20, verbose_name='Пароль пользователя')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Цена товара')),
                ('characteristics', models.TextField(max_length=5000, verbose_name='Характеристики товара')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.DO_NOTHING, to='ozon.category', verbose_name='Категория товара')),
            ],
        ),
    ]
