# Generated by Django 4.1.2 on 2022-12-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='id_product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='id_user',
        ),
    ]
