# Generated by Django 4.1.2 on 2022-12-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0005_sell_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id_user',
            field=models.IntegerField(verbose_name='Пользователь'),
        ),
    ]
