# Generated by Django 4.1.2 on 2022-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
