# Generated by Django 4.1.2 on 2022-12-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0004_rename_product_cart_id_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='Пользователь')),
                ('sell_date', models.DateTimeField(auto_now=True, verbose_name='Дата продажи')),
                ('status', models.IntegerField(verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(db_column='manga', on_delete=django.db.models.deletion.DO_NOTHING, to='ozon.product', verbose_name='Товар')),
                ('sell', models.ForeignKey(db_column='sell', on_delete=django.db.models.deletion.DO_NOTHING, to='ozon.sell', verbose_name='Продажа')),
            ],
        ),
    ]
