# Generated by Django 4.1.2 on 2022-12-25 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0006_alter_cart_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='ozon.product', verbose_name='Товар'),
        ),
    ]
